default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: shion
  password: postgres
  pool: 5

development:
  <<: *default
  database: rails-react-app_development

test:
  <<: *default
  database: rails-react-app_test
